google_analytics_url = "https://script.google.com/macros/s/AKfycbxVHsmwJRFTe5GJFIr-X0e9R5yXh3qgi1foeQqQZ61RmIuf6Lb4zN_Dnol0JEqnWMzc/exec"

analytics_sheet_csv_url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRVvCp9A5UXBo83XkbkVCGmTt9SROIds-I3HAhte7Mu8pOO3PUwZlzZ3K88VnHM9c0_bEHsQ2aymZ4Q/pubhtml?gid=0&single=true"
